--- #YAML:1.0
name:                Acme-Geo-Whitwell-Name
version:             0.02
abstract:            Steadman Whitwell's "rational geographic nomenclature"
license:             ~
author:              
    - Joe McMahon <mcmahon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
